import fs from "fs"
import path from "path"
import { shell, dialog } from "electron"

const registerFilesystemIPC = (ipcMain) => {

    ipcMain.handle("filesystem:file-exists", async (_, filePath) => {
        return fs.existsSync(filePath);
    });

    ipcMain.handle("filesystem:save-file-to-destination", async (_, { sourcePath, destinationPath }) => {
        try {
            if (!fs.existsSync(sourcePath)) {
                return { success: false, error: "Source file generated by backend does not exist." };
            }

            // Physically copies the file from your temporary backend folder to the user's chosen location
            fs.copyFileSync(sourcePath, destinationPath);
            return { success: true };
        } catch (error) {
            console.error("Failed to copy file to destination:", error);
            return { success: false, error: error.message };
        }
    });

    ipcMain.handle("dialog:save-file", async (event, options) => {
        let defaultPath = options.defaultPath || "";
        const fileType = options.fileType; // 'excel' or 'pdf'

        let systemFilters = [];

        // ─── FORCE FILE PATHS TO CONTAIN EXTENSIONS TO PREVENT WINDOWS DROPS ───
        if (fileType === 'excel') {
            systemFilters = [
                { name: 'Excel Workbooks (*.xlsx)', extensions: ['xlsx'] },
                { name: 'All Files (*.*)', extensions: ['*'] }
            ];
            // If the path doesn't end with .xlsx, append it manually
            if (!defaultPath.toLowerCase().endsWith('.xlsx')) {
                defaultPath = `${defaultPath}.xlsx`;
            }
        } 
        else if (fileType === 'pdf') {
            systemFilters = [
                { name: 'PDF Documents (*.pdf)', extensions: ['pdf'] },
                { name: 'All Files (*.*)', extensions: ['*'] }
            ];
            // If the path doesn't end with .pdf, append it manually
            if (!defaultPath.toLowerCase().endsWith('.pdf')) {
                defaultPath = `${defaultPath}.pdf`;
            }
        } 
        else {
            systemFilters = [
                { name: 'All Files (*.*)', extensions: ['*'] }
            ];
        }

        const result = await dialog.showSaveDialog({
            title: "Save Quotation Document",
            defaultPath: path.normalize(defaultPath), // Ensures clean system backslashes
            filters: systemFilters,
            properties: ['showOverwriteConfirmation']
        });

        if (result.canceled) return { canceled: true, filePath: null };
        return { canceled: false, filePath: result.filePath };
    });

    ipcMain.handle("filesystem:open-folder", async (_, folderPath) => {
        try {
            await shell.openPath(path.normalize(folderPath));
            return { success: true };
        } catch (error) {
            return { success: false, error: error.message };
        }
    });

    ipcMain.handle("filesystem:open-explorer", async (_, filePath) => {
        try {
            if (filePath) {
                // path.normalize ensures backslashes format properly on Windows
                shell.showItemInFolder(path.normalize(filePath));
                return { success: true };
            }
            return { success: false, error: "No file path provided" };
        } catch (error) {
            console.error("Failed to open explorer:", error);
            return { success: false, error: error.message };
        }
    });


    ipcMain.handle("filesystem:create-folder", async (_, folderPath) => {

        if (!fs.existsSync(folderPath)) {
            fs.mkdirSync(folderPath, { recursive: true });
        }

        return {
            success: true
        };
    });
};

export default registerFilesystemIPC;